# Generated by Django 4.2.7 on 2023-11-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0003_remove_recipe_score_reciperating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
